apiVersion: apps/v1
kind: Deployment
metadata:
  name: codefunn-api
  labels:
    app: codefunn-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codefunn-api
  template:
    metadata:
      labels:
        app: codefunn-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions: [ { key: app, operator: In, values: [ codefunn-api ] } ]
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: codefunn-api
          image: sithixay17/codefunn:draft1
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: postgres-secret


