apiVersion: v1
kind: Service
metadata:
  name: codefunn-api
  labels:
    app: codefunn-api
spec:
  type: NodePort
  selector:
    app: codefunn-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000